// Minimal IFC 4.3 common classes and predefined types mapping
// This is a pragmatic subset to aid authoring. It is not exhaustive.
// Source inspiration: IFC4x3 schema and common usage; refine over time.

export const IFC_CLASSES: string[] = [
  "IfcWall",
  "IfcWallStandardCase",
  "IfcDoor",
  "IfcWindow",
  "IfcSlab",
  "IfcBeam",
  "IfcColumn",
  "IfcMember",
  "IfcPlate",
  "IfcCovering",
  "IfcRoof",
  "IfcStair",
  "IfcRailing",
  "IfcRamp",
  "IfcSpace",
  "IfcBuilding",
  "IfcBuildingStorey",
  "IfcSite",
  "IfcFooting",
  "IfcPile",
  "IfcFurnishingElement",
  "IfcFlowTerminal",
  "IfcDistributionElement",
  "IfcDistributionFlowElement",
  "IfcProxy",
];

// Select predefined types for common entities.
// Keys are the uppercase class names.
export const PREDEFINED_TYPES: Record<string, string[]> = {
  IFCWALL: [
    "MOVABLE",
    "PARAPET",
    "PARTITIONING",
    "PLUMBINGWALL",
    "SHEAR",
    "SOLIDWALL",
    "STANDARD",
    "POLYGONAL",
    "ELEMENTEDWALL",
    "USERDEFINED",
    "NOTDEFINED",
  ],
  IFCWALLSTANDARDCASE: ["STANDARD", "USERDEFINED", "NOTDEFINED"],
  IFCDOOR: [
    "DOOR",
    "GATE",
    "TRAPDOOR",
    "USERDEFINED",
    "NOTDEFINED",
  ],
  IFCWINDOW: ["SKYLIGHT", "LIGHTDOME", "WINDOW", "USERDEFINED", "NOTDEFINED"],
  IFCSLAB: [
    "FLOOR",
    "ROOF",
    "LANDING",
    "BASESLAB",
    "USERDEFINED",
    "NOTDEFINED",
  ],
  IFCBEAM: ["BEAM", "JOIST", "HOLLOWCORE", "LINTEL", "SPANDREL", "USERDEFINED", "NOTDEFINED"],
  IFCCOLUMN: ["COLUMN", "USERDEFINED", "NOTDEFINED"],
  IFCPLATE: ["CURTAIN_PANEL", "SHEET", "USERDEFINED", "NOTDEFINED"],
  IFCCOVERING: [
    "CEILING",
    "FLOORING",
    "CLADDING",
    "ROOFING",
    "INSULATION",
    "MEMBRANE",
    "SLEEVING",
    "WRAPPING",
    "USERDEFINED",
    "NOTDEFINED",
  ],
  IFCROOF: [
    "FLAT_ROOF",
    "SHED_ROOF",
    "GABLE_ROOF",
    "HIP_ROOF",
    "HIPPED_GABLE_ROOF",
    "GAMBREL_ROOF",
    "MANSARD_ROOF",
    "BARREL_ROOF",
    "RAINBOW_ROOF",
    "BUTTERFLY_ROOF",
    "PAVILION_ROOF",
    "DOME_ROOF",
    "FREEFORM",
    "USERDEFINED",
    "NOTDEFINED",
  ],
  IFCSTAIR: [
    "STRAIGHT_RUN_STAIR",
    "TWO_STRAIGHT_RUN_STAIR",
    "QUARTER_WINDING_STAIR",
    "QUARTER_TURN_STAIR",
    "HALF_WINDING_STAIR",
    "HALF_TURN_STAIR",
    "TWO_QUARTER_TURN_STAIR",
    "TWO_QUARTER_WINDING_STAIR",
    "THREE_QUARTER_TURN_STAIR",
    "THREE_QUARTER_WINDING_STAIR",
    "SPIRAL_STAIR",
    "DOUBLE_RETURN_STAIR",
    "CURVED_RUN_STAIR",
    "TWO_CURVED_RUN_STAIR",
    "USERDEFINED",
    "NOTDEFINED",
  ],
  IFCRAILING: ["HANDRAIL", "GUARDRAIL", "BALUSTRADE", "USERDEFINED", "NOTDEFINED"],
  IFCSPACE: ["SPACE", "GFA", "PARKING", "USERDEFINED", "NOTDEFINED"],
};

export function normalizeIfcName(v: string | undefined | null): string | undefined {
  if (!v) return undefined;
  return String(v).trim();
}

